name: GitHub-Profile-Snake

on:
  schedule: # Execute every Monday at 00:00
    - cron: "0 0 * * 1"
  
  # Allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set an output
        id: output
        run: echo "PATH_OUTPUT=profile-snake-output" >> $GITHUB_OUTPUT
    
      # SOURCE: https://raw.githubusercontent.com/Platane/Platane/master/.github/workflows/main.yml
      # Generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ${{ steps.output.outputs.PATH_OUTPUT }}/github-contribution-grid-snake.svg
            ${{ steps.output.outputs.PATH_OUTPUT }}/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Add to git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add ${{ steps.output.outputs.PATH_OUTPUT }}/*

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v6
